server:
  port: 8081
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      host: beacon-db
      port: 27017
      database: beacon
auth0:
  issuer: https://gh7-beacon.auth0.com/
  apiAudience: gh7-beacon-api
twilio:
  host: http://68.183.122.97:8081
  account:
    sid: AC5b4e5a52259290419a8761256f205e08
  auth_token: 0dda1387ab171c573b976abaf4ae4d5c
  numbers:
    outbound: +13145829012
