server:
  port: 8081
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      host: beacon-db
      port: 27017
      database: beacon
auth0:
  issuer: https://gh7-beacon.auth0.com/
  apiAudience: gh7-beacon-api
twilio:
  host: ${TWILIO_HOST}
  account:
    sid: ${TWILIO_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  numbers:
    outbound: ${TWILIO_PHONE_NUMBER}
